### ISSUE TITLE
Deployed in multiple ec2 instance

### ISSUE THREAD

**Issue by 445560292** [belaban/jgroups-docker#2]
We deploy jgroups-docker in multiple ec2 instance in AWS and we use the JDBC_PING in JGroup.
The question is how to config bind_addr in jgroup configuration file.
Could you provide an example ?

Thanks

**Comment by belaban** [comment]
How do you deploy? Do you use `--net=host`?

You need to find out the interface that works if you use (for example) `netcat` (`netcat -s` and `netcat -c`) to establish a TCP connection between 2 hosts.

That interface should be `bind_addr`. If you look at [1] (bottom of page), you can use symbolic names to pick the bind address. `JDBC_PING` picks up the bind address from the transport (`TCP`).

[1] http://www.jgroups.org/manual4/index.html#Transport
