### ISSUE TITLE
gossiprouter container image Dockerfile

### ISSUE THREAD

**Issue by hostalp** [belaban/jgroups-docker#5]
Hello,
the gossiprouter deployment (`yaml/gossiprouter.yaml`) uses your container image `belaban/gossiprouter` (https://hub.docker.com/r/belaban/gossiprouter)
Is the Dockerfile (or by looking at it, probably jib-maven-plugin configuration) available for it somewhere?
We'd like to update it (for TLS support by the way) and this would be a good starting point.

**Comment by belaban** [comment]
The GossipRouter image is created in [1], old and unmaintained... PRs are welcome!
IIRC, Infinispan also creates a GossipRouter image, as the Operator runs it. I'll ping Ryan Emerson (Red Hat) to comment here...

[1] https://github.com/jgroups-extras/gossiprouter-image

**Comment by ryanemerson** [comment]
Unfortunately the Infinispan Operator doesn't use a dedicated GossipRouter image, instead it re-uses the [Infinispan server](https://quay.io/infinispan/server/) image and calls `/opt/gossiprouter/bin/launch.sh`. You could use this for your own purposes, however you will always be constrained to the JGroups version used by the Infinispan server.

**Comment by belaban** [comment]
Ah, ok, then the changes would have to go into `gossiprouter-image`, but that shouldn't be an issue.

**Comment by hostalp** [comment]
Alright, thank you for the information. I'll close this issue. It looks like we'll avoid having to use the GossipRouter for now, but I expect to get back to it in the near future. Then we'll probably look into updating the image and the related K8s deployment resource to cover a few additional things:
- updated JGroups version
- TLS: mount keystores (incl. truststore) as K8s secrets
- easy way to customize the GossipRouter startup arguments via environment variables or K8s configmap. _By the way, is there any way how to supply the keystore/truststore passwords - other than via command line arguments that are easily visible in the process list? At least environment variables would slightly hide these values (though it isn't ideal either, the values can be still obtained)._
- additional changes to the image if some are needed to get it running in more hardened environments (OpenShift)

**Comment by belaban** [comment]
Sure. 
You could inject passwords programmatically, ie.:
`router.tls().setKeystorePassword("secret")`, but then again these need to be read by the image. I don't think this is JGroups-specific.

**Comment by hostalp** [comment]
Yes that's of course possible, but I was asking about the GossipRouter "native" support for anything such.
